### ISSUE TITLE
support long TLDs in emails

### ISSUE THREAD

**Issue by tanner0101** [vapor/validation#13]
Current email validator only supports 2-3 character long TLDs.

**Comment by 0xTim** [comment]
Email validation should just be SOMETHING@SOMETHING.SOMETHING?

**Comment by vzsg** [comment]
I've been using this regex: `[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}` (also listed on [emailregex.com](http://emailregex.com/), despite being much simpler than the 99.99% valid version).

**Comment by jnozzi** [comment]
I originally reported this bug due to trying to register for vapor.cloud using my nozzi.name vanity domain. I'm of the opinion lately that email validation should be **VERY** basic (SOMETHING@SOMETHING.SOMETHING as 0xTim commented) at submission to catch obvious problems but true validation should be done by actually sending an e-mail.

**Comment by 0xTim** [comment]
@vzsg will that regex not exclude non ascii domains, such as those with Chinese characters?

**Comment by vzsg** [comment]
Unless you want to write a Punycode encoder, I don't think it's even worth considering to be valid. 🤔 

Also, check section 3.4.1 in RFC 5322.

**Comment by tanner0101** [comment]
check out: https://github.com/vapor/validation/pull/14. i used what @vzsg supplied
